linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions: # `ignore` の代わりに `exclude-functions` を使用
      - '[rR]ead'
      - '[w|W]rite'
      - '[c|C]lose'
      - '[c|C]ommit'
      - '[r|R]ollback'
      - '[p|P]rintln'

linters:
  disable-all: true
  enable:
    - govet
    - revive
    - gocyclo
    - gofmt
    - goimports
    - errcheck
    - unconvert
    - ineffassign
    - typecheck
    - unused
    - staticcheck

run:
  deadline: 10m

issues:
  exclude-dirs:
    - vendor
    - third_party
  exclude-files:
    - ".*\\.gen\\.go"
    - ".*_test\\.go"
