version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions: # `ignore` の代わりに `exclude-functions` を使用
        - '[rR]ead'
        - '[w|W]rite'
        - '[c|C]lose'
        - '[c|C]ommit'
        - '[r|R]ollback'
        - '[p|P]rintln'
        - 'io.WriteString'
        - 'bufio.Writer.WriteRune'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.gen\.go
      - .*_test\.go
      - vendor
      - third_party
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*\.gen\.go
      - .*_test\.go
      - vendor
      - third_party
      - third_party$
      - builtin$
      - examples$
