version: 1

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/stefunny
    binary: stefunny
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: false

archives:
  - files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - CREDITS

snapshot:
  name_template: "{{ .Env.NIGHTLY_VERSION }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
