inputs:
  version:
    description: "A version to install stefunny"
    default: latest
    required: false
  version-file:
    description: "File containing the stefunny version. Example: .stefunny-version"
    required: false
  github-token:
    description: "The token used when calling GitHub API"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        github_token: ${{ inputs.github-token }}
      run: |
        set -e
        VERSION="${{ inputs.version }}"
        if [ -n "${{ inputs.version-file }}" ]; then
          VERSION="v$(cat ${{ inputs.version-file }})"
        fi
        api_request_args=("-sS")
        if [[ -n "$github_token" ]]; then
          api_request_args=("${api_request_args[@]}" -H "authorization: token $github_token")
        fi
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl "${api_request_args[@]}" https://api.github.com/repos/mashiike/stefunny/releases | jq -r '[.[]|select(.tag_name > "v0.0")|select(.prerelease==false)][0].assets[].browser_download_url|select(match("linux.amd64."))')
        else
          DOWNLOAD_URL=https://github.com/mashiike/stefunny/releases/download/${VERSION}/stefunny_${VERSION:1}_linux_amd64.tar.gz
        fi
        mkdir -p ${RUNNER_TOOL_CACHE}/stefunny
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        if [[ "${DOWNLOAD_URL}" =~ \.tar\.gz$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
          tar xzvf ${FILENAME}.tar.gz
          sudo install stefunny ${RUNNER_TOOL_CACHE}/stefunny/stefunny
        elif [[ "${DOWNLOAD_URL}" =~ \.zip$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .zip)
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} ${RUNNER_TOOL_CACHE}/stefunny/stefunny
        fi

        echo "Adding ${RUNNER_TOOL_CACHE}/stefunny to path..."
        echo "${RUNNER_TOOL_CACHE}/stefunny" >> $GITHUB_PATH
        "${RUNNER_TOOL_CACHE}/stefunny/stefunny" version
