version: "3.8"

volumes:
  gopkg:

services:
  app:
    image: golang:1.21
    volumes:
      - ".:/go/src/app:delegated"
      - "gopkg:/go/pkg"
    stdin_open: true
    working_dir: /go/src/app
    environment:
      - AWS_REGION=ap-northeast-1
    depends_on:
      - sfn_local
      - localstack
  sfn_local:
    image: amazon/aws-stepfunctions-local:1.13.2
    ports:
      - "8083:8083"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LAMBDA_ENDPOINT=http://host.docker.internal:4566
      - S3_ENDPOINT=http://host.docker.internal:4566
  localstack:
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - AWS_REGION=ap-northeast-1
      - SERVICES=lambda,s3,iam,sts,logs,events
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
