name: test action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mashiike/stefunny@main
        with:
          version: v0.4.3
      - run: |
          stefunny version 2>&1 | grep -F v0.4.3
      - uses: mashiike/stefunny@main
        with:
          version: latest
      - run: |
          stefunny version 2>&1 | grep -F v0.
